GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/4

###

DELETE http://localhost:3001/api/persons/4

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Haze"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "123-456-789"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Haze",
    "number": "123-456-789"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Haze",
    "number": "123-456-789"
}
