POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "VS Code REST client is pretty good",
    "author": "jckling",
    "url": "jckling.github.io",
    "likes": 100,
    "userId": "62cabd834ad856755f2b1e56" 
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "sekret"
}

###

POST http://localhost:3003/api/login
Content-Type: application/json

{
    "username": "root",
    "password": "wrongpassword"
}
